/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import javax.swing.JButton;
import java.awt.event.ActionListener;
/**
 *
 * @author Mahmud
 */
public class Pilihan extends javax.swing.JFrame {

    /**
     * Creates new form Pilihan
     */
    public Pilihan() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnAddPasien = new javax.swing.JButton();
        btnAddRuangan = new javax.swing.JButton();
        btnAddPeriksa = new javax.swing.JButton();
        btnAddDokter = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAddPasien.setText("Tambah Pasien");
        btnAddPasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPasienActionPerformed(evt);
            }
        });

        btnAddRuangan.setText("Tambah Ruangan");

        btnAddPeriksa.setText("Tambah Periksa");

        btnAddDokter.setText("Tambah Dokter");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddDokter)
                    .addComponent(btnAddPeriksa))
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAddPasien, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddRuangan))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddPasien)
                    .addComponent(btnAddDokter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddPeriksa)
                    .addComponent(btnAddRuangan))
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPasienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddPasienActionPerformed

    public JButton getBtnAddDokter() {
        return btnAddDokter;
    }

    public JButton getBtnAddPasien() {
        return btnAddPasien;
    }

    public JButton getBtnAddPeriksa() {
        return btnAddPeriksa;
    }

    public JButton getBtnAddRuangan() {
        return btnAddRuangan;
    }

public void addListener(ActionListener al) {
    btnAddDokter.addActionListener(al);
    btnAddPasien.addActionListener(al);
    btnAddPeriksa.addActionListener(al);
    btnAddRuangan.addActionListener(al);
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDokter;
    private javax.swing.JButton btnAddPasien;
    private javax.swing.JButton btnAddPeriksa;
    private javax.swing.JButton btnAddRuangan;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
